name: shader_prototypes
description: "A new Flutter package project."
version: 0.0.1
repository: https://github.com/flar/shader_prototypes

environment:
  sdk: ^3.10.0-268.0.dev
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  logging: ^1.3.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  generate_prototypes:
