name: simple_shader
description: "A sample app using shader_prototypes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-169.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shader_prototypes:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/my_shader.frag

shader_prototypes:
  output: lib/gen/shaders
  update-gitignore: false
